### PR TITLE
UCLouvain slurm

### PR DESCRIPTION
**Pull request by vischia**
Hi @gpetruc ,

 I cleaned up my history (it had diverged), removed the offending "if not isNano" line that we were discussing, and tested on our slurm the code.

It's now ready again for review.

Also tagging @sscruz who was interested in the slurm thing.

Cheers,
Pietro

### CODE REVIEW

**Comment by sscruz** [comment]
@vischia , is it possible to make it more general so it can also be ran in a partition that is not cp3?

**Comment by vischia** [comment]
@sscruz if there is no conflict between Oviedo's slurm system and the other settings, I can rename "--env uclouvain" in "--env slurm" and set the partition to options.queue. Would that work for you?

**Comment by vischia** [comment]
(that way we would run with ```--env slurm -q cp3``` and you with ```--env slurm -q whatever```)

**Comment by sscruz** [comment]
yes, that'd be fine! Thanks!

**Pull request merged**
