### PR TITLE
TTHAnalysis data

### PR DESCRIPTION
**Pull request by gpetruc**
Fake PR 4/N out of the peruzzim:80X_M17 branch, for review.
@peruzzim @mariadalfonso

### CODE REVIEW

**Comment by gpetruc** [comment]
For _TTHAnalysis/data/btag_
- do we really need all those different files for fastsim? if not, can we keep only the one to be used?
  - can you rename the fastsim files to have a fast sim in the name or move them from`data/btag` to `data/btag/fastsim` ?
  - can you remove the non-final versions of the scale factors?
    tagging @stiegerb and @cheidegg since most of the files there are from you (https://github.com/peruzzim/cmgtools-lite/pull/53 and https://github.com/ECOP/cmgtools-lite/pull/39)

**Comment by gpetruc** [comment]
can we remove all obsolete and unneded files (e.g. under fakerate, sos_lepton_SF, jsons, ...)
tagging also @rcastello

**Comment by rcastello** [comment]
@gpetruc , sure I will do it by removing the old intermediate files used for the top up and keeping only the final ones used for ICHEP (and maybe renaming them with a proper name). Would it be ok?

**Comment by rcastello** [comment]
@gpetruc , I told @cbotta which files to remove and she kindly did it in this last commit here: https://github.com/peruzzim/cmgtools-lite/pull/74

**Pull request closed without merging**
